default_platform(:ios)

platform :ios do
  desc "Test lane for staging"
  lane :staging do
    puts "Running staging deployment"
  end

  desc "Test lane for production"
  lane :production do
    puts "Running production deployment"
  end
end

platform :android do
  desc "Test lane for staging"
  lane :staging do
    puts "Running staging deployment"
  end

  desc "Test lane for production"
  lane :production do
    puts "Running production deployment"
  end
end 