name: CI/CD

on:
  push:
    branches: [ main, development, staging, production ]
  pull_request:
    branches: [ main, development, staging, production ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install
        bundle install

    - name: Run tests
      run: npm test
        
    - name: Build Android
      run: cd android && ./gradlew assembleRelease

    - name: Build iOS
      run: cd ios && xcodebuild -workspace AIApp.xcworkspace -scheme AIApp -configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-builds
        path: |
          android/app/build/outputs/apk/release/
          ios/build/Release-iphoneos/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: app-builds

    - name: Copy environment file
      run: cp .env.staging .env
        
    - name: Deploy with Fastlane
      run: |
        bundle exec fastlane ios staging
        bundle exec fastlane android staging 